import Head from "next/head";
import { useState, useEffect } from "react";

import { InfoConnection } from "../components/InfoConnection";

export default function Connection() {
  const [tab, setTab] = useState("list");
  useEffect(() => {}, []);

  const tabAction = (tabId: string) => {
    setTab(tabId);
  };

  return (
    <>
      <Head>
        <title>Create plan info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <InfoConnection />
      </main>
    </>
  );
}
