import Head from "next/head";

import { HigherRankFactorization } from "../components/HigherRankFactorization";
import { getPath } from "../util/lib";

export default function HigherRank() {
  return (
    <>
      <Head>
        <title>{getPath()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HigherRankFactorization />
      </main>
    </>
  );
}
