import { useEffect, useState } from "react";
import Head from "next/head";
import type { GetServerSideProps } from "next";
import { initializeStore } from "../store/store";
import { getPath } from "../util/lib";
import { SideMenu } from "../components/SideMenu";
import { ControlView } from "../components/ControlView";

export default function ManagementScreen() {
  return (
    <>
      <Head>
        <title>{getPath()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SideMenu />
        <ControlView />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const zustandStore = initializeStore();

  return {
    props: {
      initialZustandState: JSON.parse(JSON.stringify(zustandStore.getState())),
    },
  };
};
