import Head from "next/head";
import { useState, useEffect } from "react";

import { MethodListView } from "../components/MethodListView";
import { MethodEdit } from "../components/MethodEdit";

export default function Method() {
  const [tab, setTab] = useState("view");
  useEffect(() => {}, []);

  const tabAction = (tabId: string) => {
    setTab(tabId);
  };

  return (
    <>
      <Head>
        <title>Create plan info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="btn-area">
          <button className="btn" onClick={() => tabAction("view")}>
            list
          </button>
          <button className="btn" onClick={() => tabAction("add")}>
            add
          </button>
        </div>
        {tab === "view" && <MethodListView />}
        {tab === "add" && <MethodEdit type={tab} />}
      </main>
    </>
  );
}
