import Head from "next/head";
import { useState, useEffect } from "react";

import { ImageListView } from "../components/ImageListView";
import { ImageMaker } from "../components/ImageMaker";
import { FileUploader } from "../components/FileUploader";

export default function Method() {
  const [tab, setTab] = useState("view");
  useEffect(() => {}, []);

  const tabAction = (tabId: string) => {
    setTab(tabId);
  };

  return (
    <>
      <Head>
        <title>Create plan info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="btn-area">
          <button className="btn" onClick={() => tabAction("viewImage")}>
            list(image)
          </button>
          <button className="btn" onClick={() => tabAction("viewMovie")}>
            list(movie)
          </button>
          <button className="btn" onClick={() => tabAction("photo")}>
            add (photo)
          </button>
          <button className="btn" onClick={() => tabAction("movie")}>
            add (movie)
          </button>
        </div>
        {tab === "viewImage" && <ImageListView type={tab} />}
        {tab === "viewMovie" && <ImageListView type={tab} />}
        {tab === "photo" && <ImageMaker type={tab} />}
        {tab === "movie" && <FileUploader type={tab} />}
      </main>
    </>
  );
}
