import Head from "next/head";
import { useState, useEffect } from "react";

import { TaskListView } from "../components/TaskListView";
import { TaskEdit } from "../components/TaskEdit";
import { getPath } from "../util/lib";

export default function Task() {
  const [tab, setTab] = useState("view");
  useEffect(() => {}, []);

  const tabAction = (tabId: string) => {
    setTab(tabId);
  };

  return (
    <>
      <Head>
        <title>{getPath()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="btn-area">
          <button className="btn" onClick={() => tabAction("view")}>
            list
          </button>
          <button className="btn" onClick={() => tabAction("add")}>
            add
          </button>
        </div>
        {tab === "view" && <TaskListView />}
        {tab === "add" && <TaskEdit type={tab} />}
      </main>
    </>
  );
}
